### ISSUE TITLE
Inconsistent between Clojure and ClojureScript, and also with standard sets

### ISSUE THREAD

**Issue by jmmk** [martinklepsch/custom-comparator-set#6]
Two different parts to this, but they are related.
#### 1. Semantics differ from normal sets

In the README, there is a short section on "Differences to regular sets". This section describes a semantic difference in "get" where you can look up a set member by its comparator value, sort of a _find-by-comparator_, instead of the normal operation which is _find-by-value_. I'm not sure I understand the reasoning behind this. The element returned by the comparator function is not a member of the set, it is used only to check uniqueness in the set. So I would expect both `contains?` and `get` to require `v` and never `(comparator v)`.
#### 2. Difference in implementation of Clj and Cljs

There is a discrepancy in the behavior of `contains?` between the Clojure and ClojureScript implementations. `(contains? (ccset/custom-comparator-set :k {:k "a"}) {:k "a"})` returns `true` for Clojure and `false` for ClojureScript.

impl.clj defines `contains` as `(contains? data-map (comparator v))` and `get` as `(get data-map v)`, where the `get` function supports the aforementioned semantics of _find-by-comparator_, but `contains` uses _find-by-value_.

impl.cljs defines `-lookup` as `(-lookup data-map v)` which is _find-by-comparator_. The difference here is that `-lookup` is used both both `get` and `contains?` for cljs.

The effects of this are:
1. Inconsistent with the standard collections
2. Inconsistent between different functions (`get` and `contains?`)
3. The Cljs version of `conj` will always assoc the value given to it
#### What to do?

I'd be happy to put in a PR for this, but I'd like to know where you stand on the semantic concerns where the custom-comparator-set currently differs from normal sets. My opinion is that set lookups should use the value, not the comparator-returned value (the implementation will run the comparator).

**Comment by martinklepsch** [comment]
@jmmk thanks for your thoughts on this. I definitely agree that the two
implementations should be consistent.

The current state is probably a result of my need for "a map with derived
keys that can easily be iterated over".

What I like about the by comparator lookup is that you can easily look
things up without knowing the complete value. I wonder if allowing just
passing something like `{:id "xyz"}` to `get` and `contains?` to achieve
the same would be a good idea. Since usually `contains?` checks values in a
set it seems strange but that's also the area where we're departing from
set behavior.

I think overall this seems like it should be fixed so a PR would be most
welcome :) Tests for the currently failing conj behavior would also be a
good idea I guess.

PS. I think the second paragraph in the second part of your message is
twisted? I.e. `get` uses find-by-value..

**Comment by jmmk** [comment]
Maybe those expressions weren't the best - what I meant by _find-by-comparator_ was that the lookup was being done using the result of `(comparator v)` by the programmer. The `get` test explains it well I think: 

``` clojure
(t/is (= {:k "b"}
  (-> (ccset/custom-comparator-set :k {:k "a"} {:k "b"})
    (get "b"))))
```

and _find-by-value_ meaning using the value itself like this:

``` clojure
(-> (ccset/custom-comparator-set :k {:k "a"})
  (get {:k "a"}))
```

I agree that lookups seem a little strange. It doesn't use equality comparisons, so the full value isn't necessary - only a minimal slice of the set to satisfy the comparator function. For example, both of these would be true:

``` clojure
(contains? (ccset/custom-comparator-set :k {:k "a" :other :key}) {:k "a" :other :key})
(contains? (ccset/custom-comparator-set :k {:k "a" :other :key}) {:k "a"})
```

But I think it's fine because the purpose is to maintain uniqueness solely based on the comparator.

**Comment by martinklepsch** [comment]
Agreed. I think we're on the same page then :)

Go ahead of you like, if you're interested I can also add you as a
collaborator so you get push access/are allowed to merge PRs.

Please use PRs in any case for greater visibility :)
